name: Generate IAC RSS Feed

on:
  schedule:
    - cron: '10 1 * * *'      # JST 10:10 毎日
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps
        run: python -m pip install --upgrade requests beautifulsoup4 lxml

      - name: Build RSS via Python
        run: |
          python <<'PY'
          import requests, datetime, email.utils, pathlib, html
          from bs4 import BeautifulSoup

          BASE = "https://iac.kyoto-u.ac.jp"
          html_text = requests.get(f"{BASE}/news-topics/").text
          soup = BeautifulSoup(html_text, "lxml")

          items_xml = []
          for art in soup.select("div.postBandWrap article"):
              a_tag  = art.find("a")
              link   = a_tag["href"]
              if link.startswith("/"):
                  link = BASE + link
              title  = a_tag.find("h2").get_text(strip=True)
              date_s = a_tag.find("time")["datetime"]  # ISO 2025-04-23
              dt     = datetime.datetime.fromisoformat(date_s)
              pub    = email.utils.format_datetime(dt)

              items_xml.append(
                  f"<item><title>{html.escape(title)}</title>"
                  f"<link>{link}</link><pubDate>{pub}</pubDate></item>"
              )

          rss = (
              '<?xml version="1.0" encoding="UTF-8"?>'
              '<rss version="2.0"><channel>'
              '<title>IAC NEWS</title>'
              '<link>https://iac.kyoto-u.ac.jp/news-topics/</link>'
              '<description>京都大学IACの最新ニュース</description>'
              + "".join(items_xml) +
              '</channel></rss>'
          )

          pathlib.Path("new_rss.xml").write_text(rss, encoding="utf-8")
          PY

      - name: Skip if no changes
        run: |
          if [ -f rss.xml ] && cmp -s new_rss.xml rss.xml; then
            echo "No change"; exit 0; fi
          mv new_rss.xml rss.xml

      - name: Commit & push
        run: |
          if git diff --quiet rss.xml; then
            echo "No diff"; exit 0; fi
          git config --global user.name  github-actions
          git config --global user.email github-actions@github.com
          git add rss.xml
          git commit -m "Update RSS"
          git push
